### PR TITLE
package g0v.json to npm

### PR DESCRIPTION
**Pull request by shelling**
This will be better to get json content from full frontend projects. Otherwise, it requires your to get the schema via ajax.

### CODE REVIEW

**Comment by shelling** [comment]
@ronnywang @poga @zbryikt please take a look. This is going to distributed schema for using in both node.js backend and webpack frontend.

**Comment by shelling** [comment]
@ronnywang @poga @zbryikt If there is no question on code review, I will merge this PR tonight.

**Comment by poga** [comment]
👍

**Comment by zbryikt** [comment]
(y)

**Pull request merged**
